name: superindo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 2.0.3
  provider: 6.0.2
  retrofit: 3.0.1+1
  shimmer: 2.0.0
  infinite_scroll_pagination: 3.1.0
  cached_network_image: 3.2.0
  auto_route: 3.2.4
  google_fonts: 3.0.0
  flutter_multi_formatter: 2.5.1
  flutter_screenutil: 5.5.3+2

dev_dependencies:
  build_runner: 2.1.11
  flutter_lints: 1.0.4
  flutter_test:
    sdk: flutter
  freezed: 2.0.3+1
  get_it: 7.2.0
  injectable: 1.5.3
  injectable_generator: 1.5.3
  json_serializable: 6.2.0
  retrofit_generator: 4.0.1
  auto_route_generator: 3.2.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
